apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: cimsi-chat
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: carliwi97/cimsi-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: cimsi-config
              key: BACKEND_URL
        - name: MONGO_URL
          value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service:27017/$(MONGO_DB_NAME)"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: cimsi-config
              key: MONGO_DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cimsi-chat
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP