apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: cimsi-chat
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg== # Base64-encoded string of "mongodbadmin"
  MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlcGFzc3dvcmQ= # Base64-encoded string of "securepassword"